import 'dart:io';

/// Checks that no Dart file in lib/ exceeds the line-count threshold.
/// Run from project root: dart run tool/check_complexity.dart
///
/// Exit code 1 if any non-whitelisted file exceeds [maxLines]. Files listed in
/// `tool/.complexity_baseline.txt` are warn-only — that captures known
/// technical debt without blocking CI, while still enforcing the cap for new
/// files. To regenerate the baseline (e.g. after a deliberate split), pass
/// `--write-baseline`.
void main(List<String> args) {
  const maxLines = 500;
  const baselinePath = 'tool/.complexity_baseline.txt';
  final writeBaseline = args.contains('--write-baseline');

  final libDir = Directory('lib');
  if (!libDir.existsSync()) {
    stderr.writeln('[complexity] lib/ not found');
    exit(1);
  }

  final whitelist = _loadBaseline(baselinePath);
  final offenders = <_Offender>[];

  for (final entity in libDir.listSync(recursive: true)) {
    if (entity is! File || !entity.path.endsWith('.dart')) continue;
    final lines = entity.readAsLinesSync().length;
    if (lines > maxLines) {
      offenders.add(_Offender(_normalize(entity.path), lines));
    }
  }

  if (writeBaseline) {
    final out = File(baselinePath);
    final sorted = offenders.map((o) => o.path).toList()..sort();
    out.writeAsStringSync(
      '# Files exempt from complexity guard (warn-only). Generated by '
      '`dart run tool/check_complexity.dart --write-baseline`.\n'
      '# Threshold: > $maxLines LOC. Aim to shrink this list, not grow it.\n'
      '${sorted.join('\n')}\n',
    );
    stdout.writeln('[complexity] wrote ${sorted.length} entries to $baselinePath');
    return;
  }

  var enforced = 0;
  for (final o in offenders) {
    if (whitelist.contains(o.path)) {
      stdout.writeln('[complexity] (baseline) ${o.path}: ${o.lines} LOC');
    } else {
      stderr.writeln('[complexity] ${o.path}: ${o.lines} LOC (> $maxLines)');
      enforced++;
    }
  }
  if (enforced > 0) {
    stderr.writeln('[complexity] $enforced file(s) over the $maxLines LOC cap and not in '
        '$baselinePath. Either split the file or — only if unavoidable — append it '
        'and explain why in the PR.');
    exit(1);
  }
}

class _Offender {
  _Offender(this.path, this.lines);
  final String path;
  final int lines;
}

Set<String> _loadBaseline(String path) {
  final f = File(path);
  if (!f.existsSync()) return <String>{};
  return f
      .readAsLinesSync()
      .map((s) => s.trim())
      .where((s) => s.isNotEmpty && !s.startsWith('#'))
      .map(_normalize)
      .toSet();
}

String _normalize(String p) => p.replaceAll('\\', '/');
